image:
  - Visual Studio 2017

environment:
  global:
    NAME: nuklear
    ASDF_SYSTEM: bodge-nuklear
    secure:
  matrix:
  - platform: x64
    TARGET_ARCH: x86_64
    CFLAGS: -m64
    PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
  - platform: x86
    TARGET_ARCH: i686
    CFLAGS: -m32
    PATH: C:\msys64\mingw32\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-i686-toolchain mingw-w64-i686-cmake

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

install:
  - git submodule update --init --recursive
  - >
    sh -c "
    pacman --needed --noconfirm -S zip unzip base-devel %PACKAGES%
    && curl -L http://bodge.borodust.org/files/install.sh | sh
    "

build_script:
  - set APPVEYOR_BUILD_DIR=$(cygpath -u '%APPVEYOR_BUILD_FOLDER%')
  - set TARGET_NAME=lib%NAME%
  - set TARGET_VERSION=%TARGET_ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - set TARGET_ARTIFACT=%TARGET_NAME%.dll-%TARGET_VERSION%
  - sh -c "CFLAGS=%CFLAGS% cd src/lib/ && make clean build"
  - mv %APPVEYOR_BUILD_FOLDER%\src\lib\%TARGET_NAME%.dll.bodged %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%

artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
